---
driver:
  name: lxd_cli

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 1
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg
  ansible_version: 2.9.11
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos-8
  - name: centos-7
#  - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
  - name: default-https
    run_list:
    attributes:
    includes:
      - centos-7
      - ubuntu-18.04
      - ubuntu-20.04
  - name: default-splash
    run_list:
    attributes:
    includes:
      - centos-7
      - ubuntu-18.04
      - ubuntu-20.04
  - name: default-clamd
    run_list:
    attributes:
    includes:
      - centos-7
      - ubuntu-18.04
      - ubuntu-20.04
