---
# https://calomel.org/squid_adservers.html
# see template/squid.conf.j2

- name: Ensure directory exists
  file:
    dest: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ scriptsdir }}"

- name: Ensure curl is present
  package:
    name: curl
    state: present

- name: add ad servers newlist script
  template:
    src: ad_servers_newlist.sh.j2
    dest: "{{ scriptsdir }}/ad_servers_newlist.sh"
    mode: '0755'

- name: add refresh cron task to refresh ads servers list
  cron:
    name: "ads servers list refresh"
    minute: "45"
    hour: "2"
    day: "*/3"
    user: "root"
    job: "{{ scriptsdir }}/ad_servers_newlist.sh > /dev/null"
    cron_file: ansible_adslist_refresh

- name: ensure ads servers list exists
  command: "sh -x {{ scriptsdir }}/ad_servers_newlist.sh"
  args:
    creates: "/var/spool/squid/ad_block.txt"
  notify:
    - restart squid
    - restart squid - docker
