---
# https://calomel.org/squid_adservers.html
# see template/squid.conf.j2

- name: Ensure directory exists
  ansible.builtin.file:
    dest: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - "{{ scriptsdir }}"

- name: Remove conflicting curl-minimal
  ansible.builtin.package:
    name: curl-minimal
    state: absent

- name: Ensure curl is present
  ansible.builtin.package:
    name: curl
    state: present

- name: Add ad servers newlist script
  ansible.builtin.template:
    src: ad_servers_newlist.sh.j2
    dest: "{{ scriptsdir }}/ad_servers_newlist.sh"
    mode: '0755'

- name: Add refresh cron task to refresh ads servers list
  ansible.builtin.cron:
    name: "ads servers list refresh"
    minute: "45"
    hour: "2"
    day: "*/3"
    user: "root"
    job: "{{ scriptsdir }}/ad_servers_newlist.sh > /dev/null"
    cron_file: ansible_adslist_refresh

- name: Ensure ads servers list exists
  ansible.builtin.command: "sh -x {{ scriptsdir }}/ad_servers_newlist.sh"
  args:
    creates: "/var/spool/squid/ad_block.txt"
  notify:
    - Restart squid
