---

- name: Set Calamaris report target
  ansible.builtin.replace:
    dest: /etc/calamaris/cron.conf
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    mode: '0644'
    backup: "{{ squid_backup | default(false) }}"
  with_items: "{{ squid_calamaris_cron_conf }}"

- name: Ensure Calamaris report directories exist
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
  with_items: "{{ squid_calamaris_dirs }}"
