---

- name: install clamav daemon package
  package:
    name: "{{ clamd_pkgs }}"
    state: present
  register: pkg_result
  until: pkg_result is success

## clamd and dansguardian need the same user to scan files
- name: clamd | review settings
  replace:
    dest: /etc/clamav/clamd.conf
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
  with_items:
    - { re: "^User .*", rep: "User {{ squid_user }}" }
    - { re: "^LocalSocketGroup .*", rep: "LocalSocketGroup {{ squid_user }}" }
# FIXME! apparmor seems to block /var/run/clamav/clamd.ctl
    - { re: "^LocalSocket .*", rep: "LocalSocket /tmp/clamd.ctl" }
  notify:
    - restart clamd

- name: clamd | check few permissions
  file: "dest={{ item.d }} state={{ item.s }} mode={{ item.m }} owner={{ squid_user }}"
  with_items:
    - { d: /var/log/clamav, s: directory, m: '0755' }
    - { d: /var/log/clamav/clamav.log, s: file, m: '0640' }

- name: check if existing signatures db
  stat: path=/var/lib/clamav/main.cvd
  register: db
- name: check if existing daily db
  stat: path=/var/lib/clamav/daily.cvd
  register: db2
- block:
    - name: stop freshclam service during update
      service: name=clamav-freshclam state=stopped
    - name: ensure signatures are present before starting clamav
      command: "freshclam"
      args:
        creates: /var/lib/clamav/daily.cvd
  when: not db.stat.exists or not db2.stat.exists

# https://bugs.launchpad.net/ubuntu/+source/clamav/+bug/1784193
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884707
#- name: Ubuntu | Switch off apparmor for clamd
#  file:
#    src: /etc/apparmor.d/usr.sbin.clamd
#    dest: /etc/apparmor.d/disable/usr.sbin.clamd
#    state: link
#  notify:
#    - remove clamd apparmor profile
#
#- meta: flush_handlers

- name: ensure clamav is started and enabled
  service: name={{ item }} state=started enabled=yes
  with_items:
    - clamav-daemon
    - clamav-freshclam
