---
# review /etc/dansguardian/lists/ for content filtering rules
# if whitelisting mode: http://askubuntu.com/questions/569102/how-to-use-dansguardian-as-a-whitelist

- name: install dansguardian package
  package: name={{ item }} state=present
  with_items:
    - dansguardian
  register: pkg_result
  until: pkg_result is success

- include: clamd.yml

- name: dansguardian | review settings
  replace:
    dest: /etc/dansguardian/dansguardian.conf
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
  with_items:
    - { re: '^UNCONFIGURED - Please remove this line', rep: '^#UNCONFIGURED - Please remove this line' }
    - { re: "^filterip =.*", rep: "filterip = {{ squid_dansguardian_filterip }}" }
#    - { re: "^proxyip =.*", rep: "proxyip = {{ squid_dansguardian_proxyip }}" }
    - { re: "^#daemonuser = 'dansguardian'", rep: "daemonuser = 'proxy'" }
    - { re: "^#daemongroup = 'dansguardian'", rep: "daemongroup = 'proxy'" }
    - { re: "^accessdeniedaddress = .*", rep: "accessdeniedaddress = '{{ squid_dansguardian_deniedaddress }}'" }
    - { re: "^loglevel = .*", rep: "loglevel = {{ squid_dansguardian_loglevel }}" }
    - { re: "^loguseragent = .*", rep: "loguseragent = on" }
    - { re: "^nologger = .*", rep: "nologger = on" }
    - { re: "#loglocation = .*", rep: "loglocation = '/var/log/dansguardian/access.log'" }
    - { re: "^language = '.*'", rep: "language = '{{ squid_dansguardian_language }}'" }
    - { re: "^#contentscanner = '/etc/dansguardian/contentscanners/clamdscan.conf'",
        rep: "contentscanner = '/etc/dansguardian/contentscanners/clamdscan.conf'"
      }
  notify:
    - restart dansguardian

- name: check few permissions
  file: "dest=/var/log/dansguardian state=directory mode=0755 owner={{ squid_user }} group={{ squid_user }}"

- name: ensure dansguardian is started and enabled
  service: name={{ item }} state=started enabled=yes
  with_items:
    - dansguardian
