---

- name: Debian | install squid
  ansible.builtin.apt:
    pkg: "{{ squid_pkgs }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: pkg_result
  until: pkg_result is success
