---

- name: install e2guardian package
  ansible.builtin.package:
    name: e2guardian
    state: present
  register: pkg_result
  until: pkg_result is success

- name: e2guardian | review settings
  ansible.builtin.replace:
    dest: /etc/e2guardian/e2guardian.conf
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    mode: '0644'
    backup: yes
  with_items:
    - { re: '^UNCONFIGURED - Please remove this line', rep: '#UNCONFIGURED - Please remove this line' }
    - { re: "^filterip =.*", rep: "filterip = {{ squid_e2guardian_filterip }}" }
    # - { re: "^proxyip =.*", rep: "proxyip = {{ squid_e2guardian_proxyip }}" }
    - { re: "^#daemonuser = 'e2guardian'", rep: "daemonuser = 'proxy'" }
    - { re: "^#daemongroup = 'e2guardian'", rep: "daemongroup = 'proxy'" }
    - { re: "^accessdeniedaddress = .*", rep: "accessdeniedaddress = '{{ squid_e2guardian_deniedaddress }}'" }
    - { re: "^loglevel = .*", rep: "loglevel = {{ squid_e2guardian_loglevel }}" }
    - { re: "^loguseragent = .*", rep: "loguseragent = on" }
    # - { re: "^nologger = .*", rep: "nologger = on" }
    - { re: "#loglocation = .*", rep: "loglocation = '/var/log/e2guardian/access.log'" }
    - { re: "^language = '.*'", rep: "language = '{{ squid_e2guardian_language }}'" }
    - { re: "^forwardedfor = .*", rep: "forwardedfor = on" }
    # - { re: "^usexforwardedfor = '.*'", rep: "usexforwardedfor = on" }
  notify:
    - restart e2guardian
    - restart e2guardian - docker

- name: check few permissions
  ansible.builtin.file: "dest=/var/log/e2guardian state=directory mode=0755 owner={{ squid_user }} group={{ squid_user }}"

- name: check log file exists
  ansible.builtin.stat:
    path: /var/log/e2guardian/access.log
  register: e2l

- name: touch log file
  ansible.builtin.file:
    path: /var/log/e2guardian/access.log
    state: touch
    owner: "{{ squid_user }}"
    mode: '0644'
  when: not e2l.stat.exists

- name: Ensure log file has right permissions
  ansible.builtin.file:
    path: /var/log/e2guardian/access.log
    owner: "{{ squid_user }}"
    mode: '0644'

- name: Set domainsnobypass
  ansible.builtin.template:
    src: "{{ squid_e2guardian_nobypass_template | default('e2guardian-domainsnobypass.j2') }}"
    dest: /etc/e2guardian/lists/domainsnobypass
    owner: "{{ squid_user }}"
    mode: '0600'

- import_tasks: e2guardian-template.yml

- name: ensure e2guardian is started and enabled
  ansible.builtin.service:
    name: e2guardian
    state: started
    enabled: yes
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )
