---

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: >
    ((ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
      and not squid_https
    )

- include: debian-https.yml
  when: >
    (
      ansible_distribution == 'Debian' or
      (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 18)
    )
    and squid_https

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: https.yml
  when: squid_https|bool

- include: ads.yml
  when: squid_filter_ads is defined and squid_filter_ads

- name: update configuration
  template:
    src: "{{ squidconf_template }}"
    dest: "{{ squid_confdir }}/squid.conf"
    owner: root
    group: root
    mode: '0644'
    validate: squid -k parse -f %s
    backup: yes
  notify: restart squid

- name: ensure log dir exists
  file:
    dest: "{{ squid_customlog_path | dirname }}"
    state: directory
    mode: '0755'
    owner: "{{ squid_user }}"
  when: squid_customlog_path is defined and squid_customlog_path

## http://wiki.squid-cache.org/Features/CustomErrors
- name: remove squid signature from templates
  replace:
    dest: "{{ item }}"
    regexp: '<p>Generated %T by %h \(%s\)</p>'
    replace: '<p>Generated %T by %h (Squid Proxy)</p>'
## Note: backup is generating mess if rerun as we are not differencing files from their backup...
#    backup=yes
  with_fileglob:
    - "{{ squid_errors_template }}en/ERR_*"

- name: copy script for transparent proxy user
  copy: src=transparent-user.sh dest=/usr/local/bin/transparent-user.sh mode=0755

- include: dansguardian.yml
  when: squid_urlfiltering_enable is defined and squid_urlfiltering_enable and squid_urlfiltering_tool == 'dansguardian'

- include: e2guardian.yml
  when: squid_urlfiltering_enable is defined and squid_urlfiltering_enable and squid_urlfiltering_tool == 'e2guardian'

- include: squidguard.yml
  when: squid_urlfiltering_enable is defined and squid_urlfiltering_enable and squid_urlfiltering_tool == 'squidguard'

- include: splash.yml
  when: squid_splash_enable|bool

- name: enable and start squid service
  service:
    name: "{{ squid_svc }}"
    state: started
    enabled: yes

- include: rsyslog.yml

- include: cgroups.yml
  when: squid_cgroups_restriction_enable|bool

- include: systemd.yml
  when: squid_systemd_restriction_enable|bool

- include: calamaris.yml
  when: squid_calamaris_enable|bool and ansible_os_family == "Debian"

- include: sarg.yml
  when: squid_sarg_enable|bool and ansible_os_family == "Debian"

- include: testing.yml
  when: squid_testing|bool

- meta: flush_handlers

- name: Ensure clamd available before ending
  wait_for:
    path: /tmp/clamd.ctl
  when: squid_urlfiltering_enable is defined and squid_urlfiltering_enable and squid_urlfiltering_tool == 'dansguardian' and squid_dansguardian_clamd
