---

# https://www.jeffgeerling.com/blog/2023/how-solve-error-externally-managed-environment-when-installing-pip3
- name: Ignore PEP 668
  ansible.builtin.file:
    path: "/usr/lib/python{{ vivisect_python_version | default('3.12') }}/EXTERNALLY-MANAGED"
    state: absent
  when: >
    (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 24) or
    (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 12)
