---

- name: yum | install squid and dependencies
  yum:
    name: "{{ squid_pkgs }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- name: RHEL7 | Install certifi
  pip:
    name: certifi
    state: present
    executable: "{{ python_pip | default('pip3') }}"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
