---

- name: yum | install squid
  yum: pkg=squid state=installed

- set_fact:
    squid_confdir: /etc/squid
    squid_svc: squid
    squid_spool: /var/spool/squid

- name: enable and start squid service
  service: name="{{ squid_svc }}" state=started enabled=yes

