---

- name: Ensure /usr/local/scripts exists
  ansible.builtin.file:
    dest: /usr/local/scripts
    state: directory
    mode: '0755'

- name: Ensure reporting script exists
  ansible.builtin.template:
    src: "{{ squid_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ squid_reporting_template | basename }}"
    mode: '0755'

- name: Add squid report in logrotate
  ansible.builtin.template:
    src: logrotate-squid.j2
    dest: /etc/logrotate.d/squid
    mode: '0644'
