---

- name: Install splash page
  template:
    src: "{{ squid_splash_template }}"
    dest: "/var/www/html/{{ squid_splash_template | regex_replace('.j2$', '') }}"
    mode: '0644'

- name: Ensure squid session directory exists
  file:
    dest: /var/lib/squid
    state: directory
    mode: '0755'
    owner: "{{ squid_user }}"
    group: "{{ squid_user }}"

- name: Check if squid session file
  stat:
    path: /var/lib/squid/session.db
  register: sessiondb

- name: Ensure squid session file exists
  file:
    dest: /var/lib/squid/session.db
    state: touch
    mode: '0600'
    owner: "{{ squid_user }}"
    group: "{{ squid_user }}"
  when: not sessiondb.stat.exists
