---
## FIXME! Work in progress/incomplete compare to dansguardian

- name: Install squidguard package
  ansible.builtin.package:
    name: "{{ squidguard_pkgs }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Squidguard | fix configuration issues
  ansible.builtin.replace:
    dest: /etc/squid/squidGuard.conf
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    mode: '0644'
  with_items:
    - { re: '^dbhome .*', rep: 'dbhome /var/lib/squidGuard' }

- name: Squidguard | enable refresh cron task
  ansible.builtin.replace:
    dest: /etc/cron.daily/squidGuard
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    mode: '0644'
  with_items:
    - { re: '^ENABLED=.*', rep: 'ENABLED=1' }
    # teledanmark down, new list from http://www.squidguard.org/blacklists.html
    - { re: 'http://ftp.teledanmark.no/pub/www/proxy/squidguard/contrib/blacklists.tar.gz',
        rep: 'http://squidguard.mesd.k12.or.us/blacklists.tgz'
    }

- name: Squidguard | initialize db
  # command: "squidGuard -C all"
  ansible.builtin.command: sh /etc/cron.daily/squidGuard
  args:
    creates: /var/lib/squidGuard/blacklists/adult/domains

- name: Check few directories
  ansible.builtin.file: "dest={{ item }} state=directory mode=0755 owner={{ squid_user }} group={{ squid_user }}"
  with_items:
    - /var/lib/squidGuard/blacklists/porn
    - /var/lib/squidGuard/blacklists/adult

- name: Ensure squidguard is started and enabled
  ansible.builtin.service: name={{ item }} state=started enabled=yes
  with_items:
    - squidGuard
