---
# FIXME! still /etc/init.d/squid on Ubuntu 18.04...

- name: Hardened options for squid systemd
  blockinfile:
    # or /etc/systemd/system/squidd.service.d/override.conf
    path: /usr/lib/systemd/system/squidd.service
    insertafter: ^KillSignal=SIGTERM
    block: |
      NoNewPrivileges=yes
      PrivateTmp=true
      PrivateDevices=true
      ProtectHome=true
      InaccessiblePaths=~/proc /run/systemd
      ProtectSystem=full
      ProtectKernelTunables=true
      RestrictRealtime=true
      RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
      SystemCallFilter=~@debug @mount @cpu-emulation @obsolete @privileged
      MemoryDenyWriteExecute=true
      PrivateMounts=true
    backup: yes
  notify:
    - reload systemd
    - restart squid
