---

- name: Set systemd override
  block:
    - name: Ensure override folder exists
      ansible.builtin.file:
        dest: /etc/systemd/system/squid.service.d
        state: directory
        mode: '0755'

    # if issue, check /var/log/audit/audit.log
    - name: Review squid systemd options - RestartSec, Seccomp...
      ansible.builtin.template:
        src: systemd-override.conf.j2
        dest: /etc/systemd/system/squid.service.d/override.conf
        mode: '0644'
      notify:
        - Reload systemd
        - Restart squid

    - name: Review squid systemd options - Source build squid
      ansible.builtin.template:
        src: systemd-override-source.conf.j2
        dest: /etc/systemd/system/squid.service.d/source-build.conf
        mode: '0644'
      notify:
        - Reload systemd
        - Restart squid
      when: >
        (
          ansible_facts['distribution'] == 'Debian' or
          (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version']|int >= 22)
        )
        and squid_https_source_build|bool

  rescue:
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system/squid.service.d
        state: pre
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system/squid.service.d/override.conf
        state: pre
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system/squid.service.d/source-build.conf
        state: pre

    - name: Ensure override folder exists - immutable
      ansible.builtin.file:
        dest: /etc/systemd/system/squid.service.d
        state: directory
        mode: '0755'

    # if issue, check /var/log/audit/audit.log
    - name: Review squid systemd options - RestartSec, Seccomp... - immutable
      ansible.builtin.template:
        src: systemd-override.conf.j2
        dest: /etc/systemd/system/squid.service.d/override.conf
        mode: '0644'
      notify:
        - Reload systemd
        - Restart squid

    - name: Review squid systemd options - Source build squid - immutable
      ansible.builtin.template:
        src: systemd-override-source.conf.j2
        dest: /etc/systemd/system/squid.service.d/source-build.conf
        mode: '0644'
      notify:
        - Reload systemd
        - Restart squid
      when: >
        (
          ansible_facts['distribution'] == 'Debian' or
          (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version']|int >= 22)
        )
        and squid_https_source_build|bool

    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system/squid.service.d
        state: post
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system/squid.service.d/override.conf
        state: post
    - name: Import immutable
      ansible.builtin.import_tasks: immutable.yml
      vars:
        target_dir: /etc/systemd/system/squid.service.d/source-build.conf
        state: post

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
