---

- name: Install testing tools
  ansible.builtin.package:
    name: "{{ squid_testing_pkgs }}"
    state: present
  register: pkg_result
  until: pkg_result is success

- import_tasks: testing-tsung.yml
  when: squid_testing_tsung
