---

- name: restart squid
  service: name="{{ squid_svc }}" state=restarted

- name: restart dansguardian
  service: name=dansguardian state=restarted

- name: restart clamd
  service: name=clamav-daemon state=restarted

- name: remove clamd apparmor profile
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.clamd

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
