---

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart squid
  service:
    name: "{{ squid_svc }}"
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart dansguardian
  service: name=dansguardian state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart e2guardian
  service: name=e2guardian state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: restart e2guardian - docker
  command: /usr/sbin/e2guardian -Q
  when: >
    (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
    )

- name: e2guardian reload
  command: e2guardian -r

- name: restart clamd
  service: name=clamav-daemon state=restarted

- name: remove clamd apparmor profile
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.clamd

- name: restart rsyslog
  service: name=rsyslog state=restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )
