---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container

- name: Restart squid
  ansible.builtin.service:
    name: "{{ squid_svc }}"
    state: restarted
  when:
    - not is_container

- name: Restart dansguardian
  ansible.builtin.service:
    name: dansguardian
    state: restarted
  when:
    - not is_container

- name: Restart e2guardian
  ansible.builtin.service:
    name: e2guardian
    state: restarted
  when:
    - not is_container

- name: Restart e2guardian - docker
  ansible.builtin.command:  # noqa no-changed-when
    cmd: /usr/sbin/e2guardian -Q
  when:
    - not is_container

- name: E2guardian reload
  ansible.builtin.command:  # noqa no-changed-when
    cmd: e2guardian -r
  when:
    - not is_container

- name: Restart clamd
  ansible.builtin.service:
    name: clamav-daemon
    state: restarted

- name: Remove clamd apparmor profile
  ansible.builtin.command:  # noqa no-changed-when
    cmd: apparmor_parser -R /etc/apparmor.d/usr.sbin.clamd

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    - not is_container

- name: Add to ca-certificates tree
  ansible.builtin.copy:
    src: "{{ ssl_dir }}/{{ site_server_name }}.crt"
    dest: "{% if ansible_os_family == 'RedHat' %}/usr/share/pki/ca-trust-source/anchors{% else %}/usr/share/ca-certificates{% endif %}"
    mode: '0644'
    remote_src: true
- name: Add to /etc/ca-certificates.conf
  ansible.builtin.lineinfile:
    path: /etc/ca-certificates.conf
    line: "{{ site_server_name }}.crt"
    mode: '0644'
    owner: root
  when: ansible_os_family == 'Debian'
- name: Update-ca-certificates
  ansible.builtin.command:  # noqa no-changed-when
    cmd: update-ca-certificates
  become: yes
  when: ansible_os_family == 'Debian'
- name: Update-ca-trust
  ansible.builtin.command:  # noqa no-changed-when
    cmd: update-ca-trust
  become: yes
  when: ansible_os_family == 'RedHat'
