---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-ubuntu:24.04}
    # env:
    #   http_proxy: ${http_proxy}
    #   https_proxy: ${https_proxy}
    #   no_proxy: ${no_proxy}
    groups:
      - molecule
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
scenario:
  name: default-stepca
verifier:
  name: ansible
