# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #config.vm.box = "ubuntu/bionic64"
    #config.vm.provision :shell, inline: "apt-get install -y python"
    #config.vm.box = "ubuntu/trusty64"
    config.vm.box = "centos/7"

    config.vm.provision :ansible do |ansible|
       ansible.compatibility_mode = "2.0"
       ansible.playbook = "site.yml"
       ansible.verbose = "vv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
       ansible.groups = {
          "myrole" => ["vhost" ],
       }
    end

    config.vm.define "vhost" do |vhost|
        vhost.vm.hostname = "vhost"
        vhost.vm.provider "virtualbox" do |v|
          v.memory = 1024
        end
    end

    config.vm.network "forwarded_port", guest: 80, host: 8180
    config.vm.network "forwarded_port", guest: 3128, host: 8128
    config.vm.network "forwarded_port", guest: 3129, host: 8129
end

