---
name: AnsibleCI

on:
  push:
  pull_request:
  schedule:  # run weekly, every monday 02:30
    - cron: '30 2 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - molecule_distro: 'centos:8'
            experimental: false
          - molecule_distro: 'centos:7'
            experimental: true
          - molecule_distro: 'ubuntu:20.04'
            experimental: false
          - molecule_distro: 'ubuntu:18.04'
            experimental: false

    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      MOLECULE_NO_LOG: "false"

    steps:
      - uses: actions/checkout@v2
        with:
          path: juju4.squid
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] ansible-lint flake8 testinfra ansible
          ansible --version
          ansible-lint --version
          mkdir -p $HOME/.ansible/roles && ln -s $GITHUB_WORKSPACE/juju4.squid $HOME/.ansible/roles/
          mkdir -p $HOME/.cache/molecule/juju4.squid/default && ln -s $HOME/.ansible/roles $HOME/.cache/molecule/juju4.squid/default/roles
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.squid && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
